### ISSUE TITLE
Peer Review - Windows

### ISSUE THREAD

**Issue by jimmy1wu** [OpenLiberty/draft-guide-social-login#10]

**Comment by jimmy1wu** [comment]
** Setting up the certificates and trust store **
- [ ] `First, navigate to the start/src/main/.../config/resources/security directory`. The resources/security folder does not exist. Prob need to add a .gitignore in that folder

- [ ] `Click on the "Lock" icon ...` That sentence does not end in a period

- [ ] `w Firefox tab titled "Certificate".` The window title is `Certificate Viewer: "*.google.com"` for google. Should change from "Certificate" to "Certificate Viewer"

- [ ] Some of the commands use ` as a line break and some use ^

- [ ] `2. Epand "Personal"` Misspelling of Expand

- [ ] `continue through the rest of the prompts in the export wizard` Maybe be a bit more specific about what i have to do here. If the values are okay as default, maybe mention "ensure that x and y are checked" in case the defaults change in future version of windows? Also mention that i have to choose a password and to remember it for the next steps.

- [ ] Have to mention that i need to export the certificate name as `certificate.pfx`

- [ ] keytool command is not working with the back ticks. "illegal option: `"

- [ ] keytool command prompts for destination keystore password, re-enter new password, and enter source keystore password. should mention that they will be prompted for these fields and what i should enter for these and/or if i need to remember them.

- [ ] Consider changing the numbered steps for OAuth 2.0 creds for google to be on separate lines.

- [ ] Numbered steps for OAuth 2.0 creds for google go from **1 -> 2 -> 1 -> 2** ->3 -> 4 ->5

- [ ] After "Fill in the "Application name", have to mention that i have to save at the bottom before the next step

- [ ] "Create Credentials" -> "CREATE CREDENTIALS",
"OAuth Client ID" -> "OAuth client ID",
"Web Application" -> "Web application"

- [ ] Link to instructions to get amazon client id & secret is outdated

- [ ] What is homepage url for getting github certs? i assume it is localhost:9080. also i assume callback url is what you called redirect url in your guide

- [ ] server.xml in start folder is missing a lot of stuff compared to the finish server.xml. I should be able to just find and replace the client id and secrets, all those fields are not in the start version along with a bunch of features

... tbd

**Comment by k-rtik** [comment]
@jimmy1wu  is it still incomplete?

**Comment by jimmy1wu** [comment]
no
