### ISSUE TITLE
Peer Review - Mac

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/draft-guide-social-login#16]
Peer Review: review to be done by a peer member. 

Functionality
---
- [ ] Check that the guide has working instructions and sample code
- [ ] Test the guide on 3 platforms: Mac, Win, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable 

Formatting & Presentation
---
- [x] Check the quality of code according to the best coding practices
    - [x] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
    - [x] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide
- [x] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [ ] Additional tests where applicable: 
    - [ ] Define test coverage and review with team (including guide contributor, if available)
    - [ ] Define detail test cases 
    - [ ] Consider corner cases targeting the specific guide
    - [ ] Consider different platform tests, ie, Mac, Windows, Linux
    - [ ] Consider corner cases UI tests
    - [ ] Consider testing URL on all browsers, ie, FF, Chrome, Safari
    - [ ] Consider testing the `curl` command for URL visits
- [ ] Consider building with both Maven and Gradle build tools 
- [ ] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [ ] Run Acrolinx Checker on draft (above 70 score approximately)
- [x] Consider SEO title and description for the guides 
- [ ] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [ ] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
    - [x] Table of contents 
    - [x] Headings
    - [x] Paragraphs
    - [x] code snippets
    - [x] outputs
    - [x] links
    - [x] hotspots 
- [x] Test the guide end-to-end with working instruction and sample code
- [ ] Perform all the defined test cases

**Comment by MaiHameed** [comment]
# What you'll learn

![image](https://user-images.githubusercontent.com/26514093/76351669-3c2eff80-62e4-11ea-922b-9ccedbc7b5f7.png)

* Should include `Amazon` in the first paragraph.

## Generating a self signed certificate
`To generate certificates for your service to use for HTTPS connections, ...`
* The command prompts the user for a password, might want to add that to the guide, similar to the next paragraph `When prompted, set the password...`
`Before the certificate and private key can be imported into the keystore for your service, ...` 
* The guide asked us to generate a certificate, where did the key come from? Might need some clarification.
```
keytool \
    -importkeystore \
    -srckeystore certificate.p12 \
    -srcstoretype PKCS12 \
    -destkeystore key.p12 \
    -deststoretype PKCS12
```
* It prompts us for multiple passwords, clarify if it's asking to set a password or to use a password we set previously

## Setting up for GitHub
```
keytool \
    -import -trustcacerts \
    -file github.pem \
    -alias github \
    -keystore slts.p12 \
    -storetype PKCS12 \
    -storepass changeit
keytool \
    -import -trustcacerts \
    -file github_api.pem \
    -alias github_api \
    -keystore slts.p12 \
    -storetype PKCS12 \
    -storepass changeit
```
* Terminal prompt `Trust this certificate? [no]:` add in the guide that it will prompt you, and to respond with `y`.

![image](https://user-images.githubusercontent.com/26514093/76352665-d0e62d00-62e5-11ea-9804-505baee44ab2.png)

* Button says "Register a new application" not "New OAuth App"
* Maybe specify somewhere in the guide that you only need to set up once using EITHER GitHub, Amazon, or Google, depending on which social service you want to use for your app.

# Configuring the security and social media login
* Probably should mention here that the user should only add the specific configuration corresponding to their social platform of choice (Amazon, GitHub, Google) to the server.xml file.

## Configuring the security roles
* The `HelloService` hotspot isn't working

## Adding [social-platform] login configuration
* Add an action block to specify that the user needs to replace the values of certain keys to keep it consistent throughout guides

# Running the application
* The `http` link doesn't work in Chrome. Throws an `Your connection is not private NET::ERR_CERT_INVALID` error. I assume it needs to be a `https` link since the rest of the links are `https`
* Getting errors when trying to access the app. 
```
[INFO] [ERROR   ] CWWKS5461E: The social login feature encountered an error while getting user information from the user API [https://api.github.com/user/emails] that is configured for social login configuration [githubLogin]. CWWKS5490E: Cannot process the response from the [https://api.github.com/user/emails] user API endpoint. The response status was [401], error was [{"message":"Requires authentication","documentation_url":"https://developer.github.com/v3/users/emails/#list-email-addresses-for-a-user"}] and the error description was [null].
[INFO] [ERROR   ] CWWKS5452E: The social login feature cannot authenticate the user because the response from the user API that is configured for the social login configuration [githubLogin] is null or empty.
```

**Comment by k-rtik** [comment]
> The `http` link doesn't work in Chrome. Throws an Your connection is not private `NET::ERR_CERT_INVALID` error. I assume it needs to be a `https` link since the rest of the links are `https`

The error is because we are using a self-signed certificate. There should be an option to continue anyway (Advanced --> Continue Anyway).
The `https` links are the endpoints used by the `socialLogin` feature. `HelloService` uses `http`
