### ISSUE TITLE
Peer Review #2 - Windows 

### ISSUE THREAD

**Issue by DannyS03** [OpenLiberty/draft-guide-social-login#17]
Peer Review: review to be done by a peer member. 

Functionality
---
- [x] Check that the guide has working instructions and sample code
- [x] Test the guide on 3 platforms: Mac, __Win__, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable 

Formatting & Presentation
---
- [x] Check the quality of code according to the best coding practices
    - [x] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
    - [x] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [ ] Examples with the right outcomes are provided
- [ ] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- guide needs to be added to guide_tags.json in guides-common dev branch for tags to appear
- [x] Check the `attribution` statement is accurate for the guide
- [x] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [x] Additional tests where applicable: 
    - [x] Define test coverage and review with team (including guide contributor, if available)
    - [x] Define detail test cases 
    - [x] Consider corner cases targeting the specific guide
    - [x] Consider different platform tests, ie, Mac, __Windows__, Linux
    - [x] Consider corner cases UI tests
    - [x] Consider testing URL on all browsers, ie, FF, Chrome, Safari
    - [x] Consider testing the `curl` command for URL visits
- [x] Consider building with both Maven and Gradle build tools 
- [x] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [x] Run Acrolinx Checker on draft (above 70 score approximately)
- [x] Consider SEO title and description for the guides 
- [x] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [x] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
    - [x] Table of contents 
    - [x] Headings
    - [x] Paragraphs
    - [x] code snippets
    - [ ] outputs
    - [x] links
    - [x] hotspots 
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases (n/a)

**Comment by DannyS03** [comment]
## What you’ll learn
- [ ] ... you can allow users to authenticate __to the__ service using social media accounts to ... you can allow users to authenticate __the__ service using social media accounts 

- [ ] `Linkedin` should be `LinkedIn`
- [ ] Mentions that LinkedIn is one of the social media dev platforms that can be used for authentication, though only three social media developer platforms are discussed (GitHub, Amazon and Google).
- [ ] `Twitter` is also one of the social media dev platforms. 
- Perhaps it would be worth discussing authentication and configuration for LinkedIn and Twitter; if the social media login feature is finite to those five platforms, it would be worth discussing, whereas if there are many social media platforms that can be used for authentication, those three would suffice as good examples to the common developer. 
  - In either case, the guide could be expressed more swiftly and concise.
  - Should consider trying to "table" or "tab" guide content for each social media developer platform; similar to the os-specific tabs, or if there is other adoc syntax to utilize. 
*******
<img width="545" alt="image" src="https://user-images.githubusercontent.com/25497083/76355745-3688e800-62eb-11ea-8c0a-1278dd77158c.png">

## Setting up the certificates and truststore

```The application you will build in this guide requires certificates for Amazon, Google and GitHub to be added to the truststore. You also need to create certificates that your application will provide for HTTPS connections. This certificate and private key will need to be added to the keystore for social media login.```

- [ ] should mention that the private key is also something that is generated [4096 bit RSA private key].
- [ ] would be good to provide an example of output(s). 

*******
<img width="551" alt="image" src="https://user-images.githubusercontent.com/25497083/76355808-53bdb680-62eb-11ea-82d8-390298f93700.png">

### Adding required features

```To enable Social Media Login feature and other required features, add new <feature /> elements to the <featureManager /> in src/main/liberty/config/server.xml```
- [ ] `src/main/liberty/config/server.xml` doesn't have to be a hotspot 

*******
<img width="514" alt="image" src="https://user-images.githubusercontent.com/25497083/76355854-633cff80-62eb-11ea-93cc-5965cadd1bde.png">

**Comment by k-rtik** [comment]
There are 5 pre-configured social media platforms, but the instructions for configuring them on the liberty side is the same. I don't know if including them will be helpful because that would just be explaining how to create an application on the other platforms.  The liberty specific instructions will be repeated; the guide is pretty repetitive as-is...
