### ISSUE TITLE
Content Review

### ISSUE THREAD

**Issue by k-rtik** [OpenLiberty/draft-guide-social-login#23]
@lauracowen 's comments about the guide:

## Content
> shouldn’t ask the user to ‘replace’ or ‘update’ files at all. They should ‘create’ the files. Then the text explains the relevant parts of the file for this guide.
> 
> The start directory (which is what they’re editing) should contain only files that are basically irrelevant to the guide. The files in the start directory are files that would be pointless for the user to create because they wouldn’t learn anything from doing so. If the file is part of the learning process (ie server.xml, HelloService.java here), they should be creating the file (even if it’s just copy/paste from the guide, it draws their attention to the specific file and what it contains). Then you explain the important bits of the file so they understand why that file is important in the context of this guide.

> would make the guide simpler/slicker if we were just to have the github one. Partly because one is simpler/shorter than two to document, and partly because the LinkedIn one says it requires setting up a company page which is a whole load of extra faff to do just to be able to do the guide.
>
> (check with [ @gkwan-ibm ]/[ @yeekangc ] the LinkedIn thing, in case there was some other reason but I’m inclined to think it’s not necessary)
>
> One thing I’d like our guides to do more is include an extra ‘task’ at the end for the user to try on their own. So you could provide guidance on how to set up github. Then, after that’s working at the end of the guide, you could briefly explain that if more than one is added, there’s a selection form presented to the user and link them to the doc on how to add more (which does actually exist here: https://www.openliberty.io/docs/ref/feature/#socialLogin-1.0.html).

> I think we can condense the github setup instructions down a bit then to something like:
> >Obtain an OAuth 2.0 client ID and client secret credentials for accessing the GitHub developer API by registering a new application in your GitHub account. On the Settings > Developer settings > OAuth Apps page of your account, register a new application. Set the Homepage URL to https://localhost:9443/. and the Authorization callback URL to https://localhost:9443/ibm/api/social-login/redirect/githubLogin . When the registration is complete, the client ID and client secret credentials are displayed on xxxxx. You’ll need these two values later in the guide to authenticate your application with GitHub.
>
> I don’t think you need the full step-by-step experience just to get the app registered - most of it’s pretty obvious - you just need to help them know what values to enter for the URLs.

## Technical
>  Don’t think you need the bit at the start about creating certificates. You should just be able to use basic tls configuration
> `<keyStore id="defaultKeyStore" password="yourPassword" />`

>  in your server.xml, I don’t think you need to specify all those features. The jwt one is automatically loaded by the social media login one (so shouldn’t need to be explicitly specified, I think). The ssl one is auto loaded by the tls one, and by the social media login one

**Comment by teddyjtorres** [comment]
SME Review: The guide looks good. A suggestion is to include markers to create particular classes since they are not under the "start" directory. Otherwise, starting the server from "start" would not give the desired behavior.

For GitHub, LinkedIn, Facebook, Twitter, and Google, please see if these are trademarked or registered and add the corresponding mark.

**Comment by teddyjtorres** [comment]
Thank you for implementing the changes. It looks good.
