### ISSUE TITLE
Acrolinx Check

### ISSUE THREAD

**Issue by NimG98** [OpenLiberty/draft-guide-social-login#31]
## What you’ll learn
- "end users" (Do not use - Deprecated Term) -> use "users"
    > It simplifies the authentication process for end users and allows you to provide a secure authentication method for your users without having to explicitly implement it.

## Creating a secured servlet
- Do not use "we", use "you"
    > We will create a servlet to handle GET requests
- change "clicking on" to "clicking"
    > When users access this endpoint by clicking on the login button

## Implementing logout
- Too complex - Clarity
    > Before the user is logged out of the application, the access token obtained by Social Login from the social media provider as part of the authentication can be used to revoke user permissions for the application
- change "logs into" to "logs in to"
    > When the user logs into the application again
- Delete this word or phrase "," - incorrect extra comma
    > Lastly, the HttpServletRequest#logout() method is used to log the user out of the application, after which the user is redirected to hello.html.

## Configuring security and social media login
- use "this" with noun
    > Adding this allows users that are authenticated using social media login to access your HelloService service.
- use "this" with noun
    > This requires the SSL certificates for GitHub to be added to a truststore.

## Next Steps
-  change "setup" to "set up"
    > You can create the <facebookLogin /> configuration element in server.xml to setup login for Facebook.

**Comment by MaiHameed** [comment]
- Be careful when you write the word using. Ensure that it is not ambiguous. https://ibmid.acrolinx.cloud/htmldata/en/rules/help/avoid_ambiguous_using.html
  > A getting started tutorial with examples on how to secure Java applications by authenticating users through social media providers, such as GitHub, using the Open Liberty Social Media Login feature.
