### ISSUE TITLE
Laura's review feedback

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/draft-guide-social-login#39]
I started reviewing but I have to review another first so here's what I had already - I will return to add more later/next week:

- "which users can use " -> "which your application users can use " maybe? Not essential but I find that we sometimes use "users" a bit loosely so it's not always clear who we mean (eg devleopers who are the users of Liberty, or end-users who use the app that the developers write using Liberty). I don't think we need to repeatedly clarify this but on this first mention maybe just make clear that we're talking about the users of the app?
- Think the URL/slug of the guide should be `social-media-login` as that's the name of the feature and technically "social" isn't a thing but "social media" is (whatever Marketing says).
- Ugh, don't think we need to trademark all those social media platform names. It looks messy and it's not necessary (check with @yeekangc or we can dig out the guidance we found last time this came up).
- "`BASIC` authentication" -> "basic authentication" (no highlighting or caps - otherwise it looks like you're talking 1980s computing...which was awesome but probably not relevant here...)
- "find the `login` button" - make sure the button label matches exactly what you say in the text (so "Login button"). Don't need to make every instance of "login button" active. But also, I'm not sure that either of these instances is appropriate to make active actually. You're not talking about the code in either case; you're talking about the UI button. If you want to say that the Login button on the page relates to the code, I think it needs to be said explicitly. eg "When you access the `hello.html` page, find the Login button, which is defined in the `button` line of the page's source code." or something...not great wording I know. I think basically in the text you're mixing in the same sentences the reader's act of accessing the hello.html page in a browser and seeing the UI with them looking at the line in the source of the hello.html page that defines that button.
- "for defaultRealm. " needs explaining - what's `defaultRealm` mean? Does the reader need to care here (ie should it be mentioned at all in this guide?)?

TBC....

**Comment by yeekangc** [comment]
Right, we shouldn't need the (R) for social platform names.

FYI, @gkwan-ibm.

**Comment by lauracowen** [comment]
Right, I've finished now. I like this guide, nice job - it takes you simply through the process. I have a bunch of mainly stylistic changes for you:

What you'll learn section:
- Remove the sentence that starts "By the end of this guide…"
- Add the following paragraph:
  "The application provided with this guide is secured through basic authentication. The application includes a simple welcome page which includes a message and a **Log in** button. The welcome page is defined in the `hello.html` (make this a hotspot to the file) file and the button is defined in the `button` (hotspot) element of that page. When the application user clicks the **Log in** button, a dialog box opens requesting the user's username and password for authenticating to the service. In this guide, you will replace the basic authentication dialog with a dialog to log in with a social media provider."
  This info is better here than in the Configuring section later (because it's not about configuring).
- Update the `hello.html` source file in the app (in both start and finish folders) so that the button is labelled `Log in` ("login" isn't a verb).

Configuring GitHub social media login section:
- The first part of this still isn't really about configuring; it's about building and running the app. So:
  - Insert before this section a new section called "Building and running the application in dev mode"
  - Move the first paragraphs (from "First, navigate to the start directory...." to "…or open the project in your editor." to the new building section.
- Change the section heading of the configuring section to "Configuring GitHub as a social media login provider"
- Then start the section with:
  "Enable the Social Media Login feature in the application by updating the `server.xml` configuration file."
- Then modify the action button:
  - Change "Update" to "Replace". We almost never "update" in the guides because it can either be confusing or gets very wordy to describe where to put the update.
  - Remove the "Add the socialLogin-1.0…." sentences from within the button area. We'll describe that below.
- After the action button,  have the description of what's important in this new version:
  "The `socialLogin-1.0` feature definition enables the Social Media Login feature in the application so that you can use the `githubLogin`  configuration element to configure GitHub as a social media login provider." Then your last paragraph as it is.
- don't include the angle brackets on the element names; ie `githubLogin` not `<githubLogin />`. It's not necessary and it adds clutter to the text.

Running… section:
- "After you log in with your GitHub account, you will need to authorize access…" to "After you log in with your GitHub account, authorize access…" (keep it present tense when describing how the tech works, and remove unnecesary words to keep it concise.
- "you created in the prerequisites section" - there is no "prerequisites" section - use the exact header name if referring back to a specific section.

Implementing logout section:
- First paragraph has some dodgy asciidoc syntax so it's not rendering correctly.
- Also, I think the first paragraph needs to mention what the app user sees relating to logging out. That is (I guess?), after clicking the **Log in** button, the button is replaced by a **Log out** button so that the app user can log out of the app and revoke permissions to their GitHub account. Does this require an update to the hello.html file orr is it handled more dynamically than that?
- "to add custom logout logic to revoke" -> "to add custom logout logic which revokes" (makes the sentence easier to read)
- "to revoke OAuth2 permissions that are granted to the application by the user." -> "to revoke the OAuth2 permissions that are granted to the application by the user." (missing word)
- "is verified by checking whether it has a 2xx series status code." - verified by what or by whom? I think it should say "is verified by the application which checks whether the response has a 2xx series status code." ?
- "`Ilogout" -> "the Ilogout interface" each time its mentioned (you have too many different objects being mentioend here to use the names without qualifyiing what they are).
- "The logoutHandler.getLogout() method returns the implementation of ILogout based on the name of the social media provider that is used by a user. " This sentence is hard to read:
  - Don't highlight "`returns`" and then use it as part of the sentence. Just write it as the word "returns" (as normal text).
  - Similarly, don't highlight "implementation" - it's just part of the sentence.
  - "the UserProfileManager" what? These guides will be translated at some point so don't assume the object name will make sense in a sentence in another language.
- In general (throuhgout the guide), don't use object names as part of the sentence "the `id` of the login configuration.". Just say "the ID of the login configuration." (without highlighting; or say "identifier" if you prefer).
- "In this case, when the user uses GitHub, the name of the social media provider is githubLogin." - I'm not sure what the "in this case" refers to or who the "user" is in this sentence. Do you mean the application for both? should it say "When the application uses GitHub as an authentication provider, the `UserProfileManager` (what?) returns the social media provider's name as `githubLogin`. Also, this sentence should be part of the previous paragraph, not in a paragraph on its own because it is part of the same discussion.
- Change the sentence before the action button to: "Implement the `Ilogout` interface to revoke permissions for the application from the user's GitHub account:"
- Why is the action to "replace" the GitHubLogout class? There's no reason for it to exist already so just make this "create" so that the reader adds the class to the application.
- Don't make random words in a sentence into hotspots. Only hotspot names of elements or methods etc that appear in the code you want to target. So:
  - "GitHub’s REST API provides a DELETE endpoint…" -> "GitHub’s REST API provides a DELETE endpoint in the `unauthorizeURL` variable…"
  - And so on for the rest of this section (and any earlier in the guide that I might have missed). Add in explicitly what part of the code you're talking about and highlight that as a hotspot. The point of the hotspots is not to make words into links but to highlight where that particular class/method/interface/whatever is mentioned in the code on the right-hand-side.
- "The Open Liberty server was started in development mode at the beginning of the guide and all the changes were automatically picked up." - Don't think you need to repeat this in full. I think just remove it. If you want, you could modify: "Check out the service that you created at http://localhost:9080/api/hello.html (all your changes were picked up automatically)."? But it shouldn't really be necessary at this stage in the guide.
- "Try logging in with your social media account. " -> "Try logging in with your GitHub account. " (there's no alternative in the app so far)
- "When you click the logout button" -> "When you click the **Log out** button"
- "As long as you are logged into GitHub, you will not be required" -> "As long as you are logged into GitHub, the application does not prompt you to…" (be more clear about what's doing what)
- "by typing q and then pressing the enter/return key." - why wouldn't `CTRL+C` work? Don't give multiple options when one will work.

Next steps section:
- Nice intro. But you don't need to give so much help - the point is for the reader to work it out for themselves.
- Remove the two paragraphs that describe how to configure the login and implement the logout.
- "The following links to Facebook documentation provides any additional information about setting up an OAuth2 application and revoking permissions." -> "See the Facebook documentation additional information about setting up an OAuth2 application and revoking permissions:"
- can you ask the website team about making those bullet points more compressed? There's too much whitespace between the items.

**Comment by lauracowen** [comment]
Looks great, thanks.
